name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set up environment variables
        run: |
            echo "PX_DB_URL=${{ secrets.PX_DB_URL }}" >> $GITHUB_ENV
            echo "PX_DB_USERNAME=${{ secrets.PX_DB_USERNAME }}" >> $GITHUB_ENV
            echo "PX_DB_PASSWORD=${{ secrets.PX_DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build -Dspring.profiles.active=test


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'